# Makefile for a samsung mipi-hsi device driver

obj-$(CONFIG_SAMSUNG_HSI) += hsi-char.o \
			hsi_driver.o \
			hsi_driver_int.o \
			hsi_debug.o \
			hsi_driver_tran.o \
			hsi-if.o \
			hsi_driver_if.o \
			hsi_memory.o

